<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="103258" started-at="2020-06-04T04:11:50Z" finished-at="2020-06-04T04:13:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="103258" started-at="2020-06-04T04:11:50Z" finished-at="2020-06-04T04:13:34Z">
      <class name="com.testdemo.TestDemo">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.testdemo.TestDemo@18be83e4]" name="openBrowser" is-config="true" duration-ms="92549" started-at="2020-06-04T04:11:50Z" finished-at="2020-06-04T04:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.testdemo.TestDemo@18be83e4]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2020-06-04T04:13:23Z" finished-at="2020-06-04T04:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="Signup1()[pri:0, instance:com.testdemo.TestDemo@18be83e4]" name="Signup1" duration-ms="10619" started-at="2020-06-04T04:13:23Z" finished-at="2020-06-04T04:13:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.generics.ExcelLibraryDemo.getcellvalue(ExcelLibraryDemo.java:13)
at com.pomdemo.POMfbLofin.signupMethod(POMfbLofin.java:50)
at com.testdemo.TestDemo.Signup1(TestDemo.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signup1 -->
      </class> <!-- com.testdemo.TestDemo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
